### ISSUE TITLE
La funcionalidad de 'favoritos' no funciona bien del todo

### ISSUE THREAD

**Issue by Diego-EC** [kholostyak17/e20-star-wars-blog#1]
https://github.com/kholostyak17/P20-Star-Wars-Blog/blob/e4fc0f3bdfbe1cefc7bd541a9dec60a5f5fa00df/src/js/store/flux.js#L10
Los favoritos si que se añaden a la lista de favoritos, pero luego no hay forma de quitarlos de la lista. Además, tampoco se quedan marcados los favoritos.

**Comment by kholostyak17** [comment]
ya está solucionado, gracias :)
